-- AlterTable
ALTER TABLE `Minuta` ADD COLUMN `imagenUrl1` VARCHAR(500) NULL,
    ADD COLUMN `publicId1` VARCHAR(300) NULL,
    ADD COLUMN `imagenUrl2` VARCHAR(500) NULL,
    ADD COLUMN `publicId2` VARCHAR(300) NULL,
    ADD COLUMN `imagenUrl3` VARCHAR(500) NULL,
    ADD COLUMN `publicId3` VARCHAR(300) NULL;
