-- AlterTable
ALTER TABLE `departamento` ADD COLUMN `planta` VARCHAR(191) NULL,
    ADD COLUMN `tipo` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `tarea` MODIFY `clasificacion` ENUM('PREVENTIVO', 'CORRECTIVO', 'INSPECCION', 'MEJORA', 'INFRAESTRUCTURA', 'RUTINA') NOT NULL DEFAULT 'CORRECTIVO';
