-- AlterTable
ALTER TABLE `tarea` ADD COLUMN `clasificacion` ENUM('PREVENTIVO', 'CORRECTIVO', 'INSPECCION', 'MEJORA', 'INFRAESTRUCTURA') NOT NULL DEFAULT 'CORRECTIVO',
    ADD COLUMN `duracionReal` INTEGER NULL DEFAULT 0,
    ADD COLUMN `tiempoEstimado` INTEGER NULL,
    ADD COLUMN `tipo` ENUM('TICKET', 'PLANEADA', 'EXTRAORDINARIA') NOT NULL DEFAULT 'TICKET';
